### ISSUE TITLE
how to delete an entry from a metrics Family

### ISSUE THREAD

**Issue by mhristache** [prometheus/client_rust#106]
I am looking for an equivalent to [`remove_label_values` ](https://docs.rs/prometheus/0.13.3/prometheus/core/struct.MetricVec.html#method.remove_label_values ) from `prometheus` crate. Is there a way to remove an entry from a metrics Family?

**Comment by phyber** [comment]
This is available in the upcoming version, but for now it's only available in the `master` branch.

https://github.com/prometheus/client_rust/blob/master/src/metrics/family.rs#L240-L260
