### ISSUE TITLE
Add `#[flatten]` directive for derivation of nested structs

### ISSUE THREAD

**Issue by howardjohn** [prometheus/client_rust#117]
Given the structs like:

```rust
struct Common {
  field_a: String,
  field_b: String,
  field_c: String
}

#[derive(Encode)]
struct Metric1 {
  unique_field: String
  #[flatten]
  common: Common
}

#[derive(Encode)]
struct Metric2 {
  unique_field_2: String
  #[serde(flatten)]
  common: Common
}
```

I want the resulting metrics:

```
metric1{field_a="foo", field_b="bar", field_c="baz",unique_field="something"}
metric2{field_a="foo", field_b="bar", field_c="baz",unique_field_2="something_else"}
```

(Note: in real world Common and the number of metrics are  much larger)

This would match the semantics of `serde(flatten)`

See https://github.com/prometheus/client_rust/pull/105#issuecomment-1340337044 for more discussion

**Comment by mxinden** [comment]
I have had that same use-case in rust-libp2p before. I am in favor of adding this to `prometheus-client-derive-encode`.

I foresee having the capacity to implement this any time soon. Focusing all my capacity on #74. @howardjohn are you interested in making the contribution?

**Comment by howardjohn** [comment]
@mxinden I sent a PR in https://github.com/prometheus/client_rust/pull/118. it might need some improvements but it works in the basic case right now, at least.
