### ISSUE TITLE
Allow multiple labels in sub_registry_with_label method

### ISSUE THREAD

**Issue by popadi** [prometheus/client_rust#144]
Hey

I have a bunch of counters coming from from processes running on different hosts and I'd like to have them labeled with about 2-3 labels to be able to query them in my dashboards. 

Is there a reason `sub_registry_with_label` accepts a single label? What if I want to add 2-3 labels to a bunch of metrics (globally)?

**Comment by mxinden** [comment]
Thanks for writing this out. Never thought there would be the need for more than one label. Happy to accept a contribution @popadi. Off the top of my head, what do you think of adding `Registry::sub_registry_with_labels` taking an `I: Iterator<Item = (Cow<'static, str>, Cow<'static, str>)>`?

**Comment by popadi** [comment]
Thanks for the quick response. I will implement this & add tests in the coming days.

**Comment by popadi** [comment]
Thanks for the quick response. I will implement this & add tests in the coming days.

I have another question (which I can move in a separate issue): is it possible to create a registry with both a prefix and one or more labels? By looking at the current implementation it seems that I have to choose one or the other.

**Comment by cratelyn** [comment]
I believe this can be closed now?

**Comment by mxinden** [comment]
True. Thanks.
