### ISSUE TITLE
Encoder without EOF

### ISSUE THREAD

**Issue by amunra** [prometheus/client_rust#153]
Hello!
I have a more uncommon use case where I'm using Rust in a multi-language setup.

The rest of the system is already serving requests to Prometheus and I'd like to slot in a few metrics for the parts of my application written in Rust.

I like that the client doesn't do HTTP serving and stick to the protocol, so it's 99% of what I need.

What causes me trouble is just a single line of code:

```rust
    writer.write_str("# EOF\n")?;
```

which prevents me from using this crate in a way that's composable with other output.

Would you consider a variant of the `encode` function that doesn't write out the `# EOF`?

Maybe called `pub fn encode_metrics`?

**Comment by amunra** [comment]
I'm happy to raise a PR, but if I am wondering if you'd have a better suggestion, especially in the context of these upcoming changes: https://github.com/prometheus/client_rust/pull/149.

**Comment by mxinden** [comment]
> I like that the client doesn't do HTTP serving and stick to the protocol, so it's 99% of what I need.

Good to hear.

> What causes me trouble is just a single line of code:
> 
> ```rust
>     writer.write_str("# EOF\n")?;
> ```

:D 

> Would you consider a variant of the `encode` function that doesn't write out the `# EOF`?

Generally yes. I see the use-case of wanting to combine multiple `encode` outputs, whether from the same client library or different ones.

That said, in case performance is not an issue for you and you are fine with a small hack, why not encode into a `String` and then drop the last line?

**Comment by mxinden** [comment]
> I'm happy to raise a PR, but if I am wondering if you'd have a better suggestion, especially in the context of these upcoming changes: #149.

I don't see how #149 would help or effect your situation. You could implement your own `Collector` that collects the metrics from the parts written in a different language. Though that sounds very painful.

**Comment by amunra** [comment]
Ours is a performance-sensitive application :-)

We embed Rust, rather than the other way around.

**Comment by amunra** [comment]
The reason why I was mentioning #149 is that as I'm looking at PR #149, the new `encode` is implemented as

```rust
/// Encode the metrics registered with the provided [`Registry`] into the
/// provided [`Write`]r using the OpenMetrics text format.
pub fn encode<W>(writer: &mut W, registry: &Registry) -> Result<(), std::fmt::Error>
where
    W: Write,
{
    registry.encode(&mut DescriptorEncoder::new(writer).into())?;
    writer.write_str("# EOF\n")?;
    Ok(())
}

pub(crate) struct DescriptorEncoder<'a> {
    writer: &'a mut dyn Write,
    prefix: Option<&'a Prefix>,
    labels: &'a [(Cow<'static, str>, Cow<'static, str>)],
}
```

The alternative here might be to expose the `DescriptorEncoder` as `pub` rather than `pub(crate)`. I think an independent function is cleaner (though I can't necessarily think of a good name).

If not, I'll wait for PR #149 to be merged and raise mine after (given that code is changing anyways).
