### ISSUE TITLE
Allow iterating the metrics on an registry

### ISSUE THREAD

**Issue by flaneur2020** [prometheus/client_rust#163]
I'm working on a database that has a built-in system table for providing metric values to users.

At present, I have to dump these metrics into a string and then parse it to retrieve the samples.

I discovered that MetricsIterator perfectly aligns with my requirements for this feature. But unfortunately, it's marked as pub(crate), which prevents me from calling this iterator externally.

I'm wondering if this limitation was intentionally by-design or not?

Thank you a lot.

**Comment by mxinden** [comment]
:wave: 

Yes, making it `pub(crate)` was a deliberate decision. The smaller the surface of this library, the easier it is to maintain and evolve it. Since https://github.com/prometheus/client_rust/pull/149 it is replaced by an alternative internal implementation and thus no longer available.
