### ISSUE TITLE
Counter `HELP` and `TYPE` lack `_total` suffix

### ISSUE THREAD

**Issue by link2xt** [prometheus/client_rust#194]
When encoding counters, `prometheus-client` adds `_total` suffix to sample name:
https://github.com/prometheus/client_rust/blob/b462e610498510cc1a4de42c7e920ba67032a493/src/encoding/text.rs#L187

This suffix is however not added in `HELP` and `TYPE` lines. This is visible in tests, for example:
https://github.com/prometheus/client_rust/blob/b462e610498510cc1a4de42c7e920ba67032a493/src/encoding/text.rs#L20-L23

`HELP` and `TYPE` lines should have the same suffix, it is shown in example at https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-example:
```
# HELP http_requests_total The total number of HTTP requests.
# TYPE http_requests_total counter
http_requests_total{method="post",code="200"} 1027 1395066363000
http_requests_total{method="post",code="400"}    3 1395066363000
```

Because of this bug Grafana does not display help for counters. At the same time for gauge type metrics help is displayed.

**Comment by mxinden** [comment]
This is inline with the OpenMetrics specification:

https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#counter-1

When exporting, are you setting the correct content type?

https://github.com/prometheus/client_rust/blob/b462e610498510cc1a4de42c7e920ba67032a493/examples/hyper.rs#L69-L70

**Comment by mxinden** [comment]
I don't feel strongly about following the specification. That said, I want to be either (a) consistent with the specification or (b) consistent with the other client implementations and ideally (a) and (b).
