### ISSUE TITLE
Hidden imports in lib.rs example code

### ISSUE THREAD

**Issue by 56quarters** [prometheus/client_rust#34]
Hello folks,

Looking at the example code in [lib.rs](https://github.com/prometheus/client_rust/blob/master/src/lib.rs) (when rendered on docs.rs), it was a little confusing to figure out what was going on due to many functions and types from the client_rust library being imported but the imports themselves being hidden.

What do you think about un-hiding the library imports so that it's more clear which parts of the client_rust library the example code is referencing?

**Comment by mxinden** [comment]
Ah you mean e.g. doing the following?

```diff
- //! # use prometheus_client::encoding::text::Encode;
+ //! use prometheus_client::encoding::text::Encode;
```

Sounds reasonable to me. Do you want to provide a patch @56quarters?

**Comment by 56quarters** [comment]
Exactly! I'll submit a PR
