### ISSUE TITLE
How can we create Prometheus Descriptors?

### ISSUE THREAD

**Issue by rajaSahil** [prometheus/client_rust#45]
All the fields present in the Prometheus Descriptor are private which doesn't allow to initialise a new desc for custom metric. Should there be a default or parametrized constructor? 

Let's say, I want to create a collector which contains different metrics and those metrics should have a new desc. How can I create one? Is the Descriptor concept fully implemented in this crate? 

Similar to this piece of code: https://github.com/tikv/rust-prometheus/blob/ac86a264223c8d918a43e739ca3c48bb4aaedb90/src/desc.rs#L86

**Comment by rajaSahil** [comment]
@mxinden Any pointer on this?

**Comment by rajaSahil** [comment]
I have been using Prometheus go-client recently and we have a concept of collectors, gatherers and descriptors. Are those concepts changed over here or is it not yet implemented?

Also can you please provide an example to use Family::metrics?

**Comment by mxinden** [comment]
> I have been using Prometheus go-client recently and we have a concept of collectors, gatherers and descriptors. Are those concepts changed over here or is it not yet implemented?

They are not present here.

> Also can you please provide an example to use Family::metrics?

You can find various examples on how to use `Family` in the documentation e.g. here https://docs.rs/prometheus-client/0.15.1/prometheus_client/metrics/family/struct.Family.html

**Comment by rajaSahil** [comment]
Thanks @mxinden . Closing this issue.
