### ISSUE TITLE
Custom encoder?

### ISSUE THREAD

**Issue by ackintosh** [prometheus/client_rust#46]
I would like to send (partial) metrics stored the `Registry` in original JSON format differ from OpenMetrics, into an endpoint different from Prometheus server. 

Here is a pseudo code, shows what I want to do:

```rust
        let mut registry = <Registry>::default();

        // (omitted)

        // Using the OpenMetrics format.
        let mut buffer = vec![];
        encode(&mut buffer, &registry).unwrap();

        // On the other hand, send (partial) metrics in JSON, into an endpoint different from Prometheus server.
        let mut data = vec![];
        for (descriptor, metric) in registry.iter() {
            if descriptor.name() == "__test__" {
                data.push(
                    translate_to_json(metric), // original JSON format
                );
            }
        }
        send(data); // send to an endpoint different from Prometheus server
```

I think I need to implement custom encoder, translate metrics to JSON format.

Please let me know if there is any good way. 🙏

**Comment by mxinden** [comment]
:wave: Hi @ackintosh,

> I think I need to implement custom encoder, translate metrics to JSON format.

Yes, you would need to implement something along the lines of https://github.com/prometheus/client_rust/blob/master/src/encoding/text.rs.

Though lots of the internals you would need are not exposed to the outside. Is this a well known format you are referring to? Would it make sense to contribute it to the library? Or would it maybe make sense to add the OpenMetrics protobuf format to this library which you could then consume and convert to your JSON output?

**Comment by ackintosh** [comment]
Hi @mxinden !

> Is this a well known format you are referring to?

As a background of I've file this issue, I'm working on [this issue](https://github.com/sigp/lighthouse/issues/2956).

The metrics I would like to send to somewhere in JSON is defined as [Ethereum consensus client metrics](https://github.com/gobitfly/eth2-client-metrics) and [Beacon chain metrics](https://github.com/ethereum/beacon-metrics/blob/master/metrics.md).


> Would it make sense to contribute it to the library? Or would it maybe make sense to add the OpenMetrics protobuf format to this library which you could then consume and convert to your JSON output?

I think the latter would be good as we can convert the metrics to JSON. though I'm not familiar with the OpenMetrics protobuf format for now. 💦

**Comment by peterbourgon** [comment]
> The metrics I would like to send to somewhere in JSON is defined as [Ethereum consensus client metrics](https://github.com/gobitfly/eth2-client-metrics) and [Beacon chain metrics](https://github.com/ethereum/beacon-metrics/blob/master/metrics.md).

This is out of scope for this crate.

**Comment by ackintosh** [comment]
I believe too that it make sense to add the OpenMetrics protobuf format to `prometheus-client`. ✨ 

> https://github.com/OpenObservability/OpenMetrics should be a good first starting point.

Thank you for the pointer! That helped a lot.

And I have noticed that prometheus-client doesn't support the OpenMetrics protobuf format due to [the issue](https://github.com/OpenObservability/OpenMetrics/issues/183). 👀

https://github.com/prometheus/client_rust#specification-compliance
> ### Specification Compliance
> - Protobuf wire format. (Follow [spec issue](https://github.com/OpenObservability/OpenMetrics/issues/183).)

**Comment by mxinden** [comment]
> And I have noticed that prometheus-client doesn't support the OpenMetrics protobuf format due to [the issue](https://github.com/OpenObservability/OpenMetrics/issues/183). eyes

That was the thing that stopped me from working on Protobuf support in `prometheus-client` back then. With the latest comments on the issue in mind, I am not sure this is still a blocker. Would you mind giving it a try, i.e. add support for Protobuf to `prometheus-client`?

**Comment by ackintosh** [comment]
Yes, I will try to add support for Protobuf. Will file a PR later. 🚀
