### ISSUE TITLE
Registry::register should not automatically append a period to the help text

### ISSUE THREAD

**Issue by 08d2** [prometheus/client_rust#56]
Help strings should end with a period, per Prometheus guidance. But if a user does that themselves, the help string will be incorrect, as "[a full stop punctuation mark (.) is automatically added to the passed help text](https://docs.rs/prometheus-client/latest/prometheus_client/registry/struct.Registry.html#method.register)" given to Registry::register.

Probably the best solution here is to append the period only if it doesn't already exist.

**Comment by mxinden** [comment]
Added to https://github.com/prometheus/client_rust/issues/52. Thanks @08d2. Let me know in case you want to tackle any of these.

**Comment by 08d2** [comment]
It should not be an error if a help string ends in a period.
