### ISSUE TITLE
Sharing dynamically dispatched registry in web framework state

### ISSUE THREAD

**Issue by sd2k** [prometheus/client_rust#57]
I may be missing something but it seems like it's not possible to use the `Registry` with the default `M = SendEncodeMetric` type as shared state in web frameworks (e.g. `tide::with_state`), because those require that the state is all `Sync` but `SendEncodeMetric` is not `Sync`. If I [update the `tide` example to use a dynamically dispatched `Registry`](https://github.com/sd2k/client_rust/commit/855f4ab5fa68caec27edbab5c8a2d47c39920010) then it fails to compile:

```
✦ ❯ cargo c --example tide
error[E0277]: `(dyn SendEncodeMetric + 'static)` cannot be shared between threads safely
   --> examples/tide.rs:25:36
    |
25  |       let mut app = tide::with_state(State {
    |  ___________________----------------_^
    | |                   |
    | |                   required by a bound introduced by this call
26  | |         registry: Arc::new(registry),
27  | |     });
    | |_____^ `(dyn SendEncodeMetric + 'static)` cannot be shared between threads safely
    |
    = help: the trait `Sync` is not implemented for `(dyn SendEncodeMetric + 'static)`
    = note: required because of the requirements on the impl of `Sync` for `Unique<(dyn SendEncodeMetric + 'static)>`
    = note: required because it appears within the type `Box<(dyn SendEncodeMetric + 'static)>`
    = note: required because it appears within the type `(Descriptor, Box<(dyn SendEncodeMetric + 'static)>)`
    = note: required because of the requirements on the impl of `Sync` for `Unique<(Descriptor, Box<(dyn SendEncodeMetric + 'static)>)>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<(Descriptor, Box<(dyn SendEncodeMetric + 'static)>)>`
    = note: required because it appears within the type `Vec<(Descriptor, Box<(dyn SendEncodeMetric + 'static)>)>`
    = note: required because it appears within the type `Registry`
    = note: required because of the requirements on the impl of `std::marker::Send` for `Arc<Registry>`
note: required because it appears within the type `State`
   --> examples/tide.rs:59:8
    |
59  | struct State {
    |        ^^^^^
note: required by a bound in `with_state`
   --> /Users/ben/.cargo/registry/src/github.com-1ecc6299db9ec823/tide-0.16.0/src/lib.rs:153:20
    |
153 |     State: Clone + Send + Sync + 'static,
    |                    ^^^^ required by this bound in `with_state`

<several related errors omitted>
```

It's fixed by adding a `Sync` bound to `SendEncodeMetric` but it feels like this is a common use case so I imagine it's come up before and I'm doing something silly - am I?

Thanks!

**Comment by mxinden** [comment]
Good catch. Thanks @sd2k. This is related to https://github.com/prometheus/client_rust/pull/55. E.g. when you wrap the `Registry` in both an `Arc` and a `Mutex`, it would compile. 

> It's fixed by adding a Sync bound to SendEncodeMetric but it feels like this is a common use case so I imagine it's come up before and I'm doing something silly - am I?

I would be OK, extending the super trait `SendEncodeMetric` to `SendSyncEncodeMetric`. I expect most folks would run `prometheus-client` in a multi-threded environment with synchronization on each metric anyways. I still want to give folks the chance to not have to pay in a single threaded setup, though that they can still do overriding the default trait parameter on `Registry`.

If you agree, want to provide a patch @sd2k?

While wrapping `Registry` in a `Mutex` and an `Arc` (see above) is an option, I would prefer to simpler `Arc` wrapper only.

**Comment by sd2k** [comment]
Sure @mxinden, sounds good to me. I've created #58 which should hopefully do the trick.

**Comment by Jc2k** [comment]
Any chance of getting a release with this fix in? It's also biting me on a Rocket project.

**Comment by mxinden** [comment]
@Jc2k see https://github.com/prometheus/client_rust/pull/59

**Comment by Jc2k** [comment]
TYVM!
