### ISSUE TITLE
Add default buckets for Histogram metric

### ISSUE THREAD

**Issue by luoxiaoyun-hw** [prometheus/client_rust#61]
Histogram metric missed default implementation，wo can add default buckets.

**Comment by doehyunbaek** [comment]
Maybe add default as in client_golang as it is the most popular client implementation?

https://github.com/prometheus/client_golang/blob/66837e3298bdc57a828794c23bacb253ed8c04cd/prometheus/histogram.go#L68

I can contribute a PR as it seems not too hard if you agree.

**Comment by luoxiaoyun-hw** [comment]
we can refer to the client_golang and client_java to provide default buckets.

**Comment by mxinden** [comment]
I would rather call this out in the documentation on `Histogram`, providing an example with the above mentioned default values. I am not in favor of adding a `Default` implementation that only works for some use-cases, here network latency measurements. I find this confusing for newcomers. Experts will be familiar enough to read the example and thus configure it themselves.

> I can contribute a PR as it seems not too hard if you agree.

Improvements to the documentation would be appreciated.

**Comment by mxinden** [comment]
With https://github.com/prometheus/client_rust/pull/63 merged, I am closing here. Feel free to follow up with further comments.
