### ISSUE TITLE
Add the implementation of exposing promethues metrics via HTTP

### ISSUE THREAD

**Issue by luoxiaoyun-hw** [prometheus/client_rust#62]
the rust client library doesn't provide the implementation of exposing promethues metrics.

**Comment by doehyunbaek** [comment]
Maybe the intent is to use separate http framework to serve metrics data? There is an example using tide(https://github.com/search?q=tide&ref=opensearch) at the examples directory(https://github.com/prometheus/client_rust/blob/master/examples/tide.rs).

**Comment by mxinden** [comment]
There is not one canonical way to do http in Rust. Thus, I would rather showcase many different use-cases in `/examples` rather than offering a single within the library.
