### ISSUE TITLE
Remove impl Add<&Prefix> for String

### ISSUE THREAD

**Issue by erenon** [prometheus/client_rust#68]
Because of https://github.com/rust-lang/rust/issues/77143, the `impl Add<&Prefix> for String` can prevent the compilation of unrelated, previously working programs, if they use string concat. This prevents adding this library to such a project, or prevents adding other deps to a project that already uses prometheus. The resulting error message is also cryptict.

Please consider removing the trait impl, thanks.

**Comment by mxinden** [comment]
I am fine removing it, especially since `Prefix` is private. Want to propose a patch @erenon?
