### ISSUE TITLE
Combining registries?

### ISSUE THREAD

**Issue by vladvasiliu** [prometheus/client_rust#73]
Is there an elegant way of combining multiple registries in a single encode output?

An example of a use case would be writing an exporter for metrics from an external system, as opposed to the own application's metrics.

The idea is that new metric families would be created and populated on each scrape. But there could also be exporter-related metrics that would be constant between scrapes, such as an info, etc.

One way of doing this right now would be to register the exporter's metrics to a new, per-scrape Registry, together with the scrape metrics and encode that. This approach seems somewhat verbose.

A more ergonomic approach would be for the encode function to take some iterable of Families and encode that, which is basically what the Registry is from its point of view.

**Comment by mxinden** [comment]
Would the `Collector` pattern be helpful here?

Proposed in https://github.com/prometheus/client_rust/issues/49

Further designed in https://github.com/prometheus/client_rust/issues/29#issuecomment-1172877769

**Comment by vladvasiliu** [comment]
Yeah, I think that could be helpful.

I'd initially glossed over these, seeing how at first they were about "custom encoders", but upon closer reading that's pretty much what I'm after.

**Comment by mxinden** [comment]
Great. Note @vladvasiliu that help here is very much appreciated.

**Comment by vladvasiliu** [comment]
Sure, I'll see if I can come up with something over the weekend.
